# post size in MiB
maxuploadsize: 25

idlength: 20

# directory to store uploaded files
storepath: 'files'

# listen address/port
listenaddr: ':8080'

tls:
    use:  false
    key:  '/etc/ssl/private/ssl-cert-snakeoil.key'
    cert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'

database:
    # see https://godoc.org/github.com/jinzhu/gorm#Open
    driver: 'sqlite3'
    args:   'gdprshare.db'

mail:
    smtphost: 'localhost'
    smtpport: 25
    smtpuser: ''
    smtppass: ''
    from:     'root@localhost'
    subject:  'File has been accessed: %s'
    subjectReceipt: 'File download confirmed: %s'

    # available variables:
    #   .FileID
    #   .Addr
    #   .UserAgent
    #   .SrcTLSVersion
    #   .SrcTLSCipherSuite
    #   .DstTLSVersion
    #   .DstTLSCipherSuite
    #   .Location.Continent
    #   .Location.Country
    #   .Location.Subdivision1
    #   .Location.Subdivision2
    #   .Location.City
    #   .Location.IsEU
    #   .DeniedMsg
    #
    # Example:
    #
    # body: |
    #     File download has been attempted.

    #     File ID: {{.FileID}}
    #     IP Address: {{.Addr}}
    #     User Agent: {{.UserAgent}}
    #     Encryption Sender: {{.SrcTLSVersion}}/{{.SrcTLSCipherSuite}}
    #     Encryption Receiver: {{.DstTLSVersion}}/{{.DstTLSCipherSuite}}

    #     {{if .Location -}}
    #     Continent: {{.Location.Continent}}
    #     Country: {{.Location.Country}}
    #     {{- if .Location.Subdivision1 }}
    #     Subdivision1: {{.Location.Subdivision1}}
    #     {{- end }}
    #     {{- if .Location.Subdivision2 }}
    #     Subdivision2: {{.Location.Subdivision2}}
    #     {{- end }}
    #     City: {{.Location.City}}
    #     {{- end }}

    #     {{.DeniedMsg}}

    body: "File download with id {{.FileID}} has been attempted. {{.DeniedMsg}}"
    deniedMsg: 'Download was denied.'


# headers in case app is behind a reverse proxy
header:
    tlsversion:     'X-TLS-Version'
    tlsciphersuite: 'X-TLS-CipherSuite'

# saves receiver IP addr and user agent in database
saveclientinfo: false

# length of password pregenerated on the frontend
passwordlength: 12

# MaxMind GeoLite2 City database path (mmdb file)
geoippath: ''


# for config via env vars see https://github.com/jinzhu/configor#advanced-usage
